//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemade.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomemadeErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomemadeErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homemade.BLL.Resources.HomemadeErrorMessages", typeof(HomemadeErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number Requierd.
        /// </summary>
        public static string AccountNumberRequierd {
            get {
                return ResourceManager.GetString("AccountNumberRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Requierd.
        /// </summary>
        public static string AddressRequierd {
            get {
                return ResourceManager.GetString("AddressRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Types Requierd.
        /// </summary>
        public static string AddressTypesRequierd {
            get {
                return ResourceManager.GetString("AddressTypesRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Requierd.
        /// </summary>
        public static string AmountRequierd {
            get {
                return ResourceManager.GetString("AmountRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount InValid.
        /// </summary>
        public static string AmountValid {
            get {
                return ResourceManager.GetString("AmountValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic letters and numbers only.
        /// </summary>
        public static string ArabicOnly {
            get {
                return ResourceManager.GetString("ArabicOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Address Requierd.
        /// </summary>
        public static string ArAddressRequierd {
            get {
                return ResourceManager.GetString("ArAddressRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name  Requierd.
        /// </summary>
        public static string ArNameRequierd {
            get {
                return ResourceManager.GetString("ArNameRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Requierd.
        /// </summary>
        public static string BankRequierd {
            get {
                return ResourceManager.GetString("BankRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Fare Required.
        /// </summary>
        public static string BaseFareRequired {
            get {
                return ResourceManager.GetString("BaseFareRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Requierd.
        /// </summary>
        public static string BlockRequierd {
            get {
                return ResourceManager.GetString("BlockRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelation Fare Required.
        /// </summary>
        public static string CancelationFareRequired {
            get {
                return ResourceManager.GetString("CancelationFareRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Car Type Required.
        /// </summary>
        public static string CategoryCarTypeRequired {
            get {
                return ResourceManager.GetString("CategoryCarTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryRequierd.
        /// </summary>
        public static string CategoryRequierd {
            get {
                return ResourceManager.GetString("CategoryRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Requierd.
        /// </summary>
        public static string CityRequierd {
            get {
                return ResourceManager.GetString("CityRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Requierd.
        /// </summary>
        public static string ClientRequierd {
            get {
                return ResourceManager.GetString("ClientRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Type Requierd.
        /// </summary>
        public static string ClientTypeRequierd {
            get {
                return ResourceManager.GetString("ClientTypeRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Required.
        /// </summary>
        public static string CodeRequired {
            get {
                return ResourceManager.GetString("CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password Requierd.
        /// </summary>
        public static string ConfirmPasswordRequierd {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Ar Requierd.
        /// </summary>
        public static string ContentArRequierd {
            get {
                return ResourceManager.GetString("ContentArRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content En Requierd.
        /// </summary>
        public static string ContentEnRequierd {
            get {
                return ResourceManager.GetString("ContentEnRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Requierd.
        /// </summary>
        public static string CountryRequierd {
            get {
                return ResourceManager.GetString("CountryRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Operation Requierd.
        /// </summary>
        public static string DateOperationRequierd {
            get {
                return ResourceManager.GetString("DateOperationRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Price Required.
        /// </summary>
        public static string DefaultPriceRequired {
            get {
                return ResourceManager.GetString("DefaultPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Price Should Be Greater Than Zero.
        /// </summary>
        public static string DeliveryPriceBiggerThanZero {
            get {
                return ResourceManager.GetString("DeliveryPriceBiggerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Price Shoud be from.
        /// </summary>
        public static string DeliveryPriceMinMaxValidation {
            get {
                return ResourceManager.GetString("DeliveryPriceMinMaxValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rial.
        /// </summary>
        public static string DeliveryPriceMinMaxValidationCurrency {
            get {
                return ResourceManager.GetString("DeliveryPriceMinMaxValidationCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string DeliveryPriceMinMaxValidationTo {
            get {
                return ResourceManager.GetString("DeliveryPriceMinMaxValidationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Price  Requierd.
        /// </summary>
        public static string DeliveryPriceRequierd {
            get {
                return ResourceManager.GetString("DeliveryPriceRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Price.
        /// </summary>
        public static string DeliveryPriceRequired {
            get {
                return ResourceManager.GetString("DeliveryPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Price Required.
        /// </summary>
        public static string DeliveryPriceValidation {
            get {
                return ResourceManager.GetString("DeliveryPriceValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Type Requierd.
        /// </summary>
        public static string DeliveryTypeRequierd {
            get {
                return ResourceManager.GetString("DeliveryTypeRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Type Required.
        /// </summary>
        public static string DeliveryTypeRequired {
            get {
                return ResourceManager.GetString("DeliveryTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Requierd.
        /// </summary>
        public static string DepartmentRequierd {
            get {
                return ResourceManager.GetString("DepartmentRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Date Required.
        /// </summary>
        public static string Discount_Date_Required {
            get {
                return ResourceManager.GetString("Discount_Date_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Requierd.
        /// </summary>
        public static string DoctorRequierd {
            get {
                return ResourceManager.GetString("DoctorRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Commision Requierd.
        /// </summary>
        public static string DriverCommisionRequierd {
            get {
                return ResourceManager.GetString("DriverCommisionRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Requierd.
        /// </summary>
        public static string DriverRequierd {
            get {
                return ResourceManager.GetString("DriverRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Invalid.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Requierd.
        /// </summary>
        public static string EmailRequierd {
            get {
                return ResourceManager.GetString("EmailRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Address Requierd.
        /// </summary>
        public static string EnAddressRequierd {
            get {
                return ResourceManager.GetString("EnAddressRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English letters and numbers only.
        /// </summary>
        public static string EnglishOnly {
            get {
                return ResourceManager.GetString("EnglishOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name Requierd.
        /// </summary>
        public static string EnNameRequierd {
            get {
                return ResourceManager.GetString("EnNameRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities Group Requierd.
        /// </summary>
        public static string EntitiesGroupRequierd {
            get {
                return ResourceManager.GetString("EntitiesGroupRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Requierd.
        /// </summary>
        public static string EntityRequierd {
            get {
                return ResourceManager.GetString("EntityRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Type Requierd.
        /// </summary>
        public static string EntityTypeRequierd {
            get {
                return ResourceManager.GetString("EntityTypeRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fare Minute Required.
        /// </summary>
        public static string FareMinuteRequired {
            get {
                return ResourceManager.GetString("FareMinuteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Requierd.
        /// </summary>
        public static string FaxRequierd {
            get {
                return ResourceManager.GetString("FaxRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Requierd.
        /// </summary>
        public static string FieldRequierd {
            get {
                return ResourceManager.GetString("FieldRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File No Requierd.
        /// </summary>
        public static string FileNoRequierd {
            get {
                return ResourceManager.GetString("FileNoRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File No InValid.
        /// </summary>
        public static string FileNoValid {
            get {
                return ResourceManager.GetString("FileNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Arabic Requierd.
        /// </summary>
        public static string FirstNameARRequierd {
            get {
                return ResourceManager.GetString("FirstNameARRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name English Requierd.
        /// </summary>
        public static string FirstNameENRequierd {
            get {
                return ResourceManager.GetString("FirstNameENRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name Requierd.
        /// </summary>
        public static string FirstNameRequierd {
            get {
                return ResourceManager.GetString("FirstNameRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender Requierd.
        /// </summary>
        public static string GenderRequierd {
            get {
                return ResourceManager.GetString("GenderRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Setting Requierd.
        /// </summary>
        public static string GeneralSettingRequierd {
            get {
                return ResourceManager.GetString("GeneralSettingRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBA Nnumber Requierd.
        /// </summary>
        public static string IBANnumberRequierd {
            get {
                return ResourceManager.GetString("IBANnumberRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID No Requierd.
        /// </summary>
        public static string IDNoRequierd {
            get {
                return ResourceManager.GetString("IDNoRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID No InValid.
        /// </summary>
        public static string IDNoValid {
            get {
                return ResourceManager.GetString("IDNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone number.
        /// </summary>
        public static string Invalid_Phone_number {
            get {
                return ResourceManager.GetString("Invalid_Phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Mobile.
        /// </summary>
        public static string InvalidMobile {
            get {
                return ResourceManager.GetString("InvalidMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree to the terms and conditions.
        /// </summary>
        public static string IsAgreeTermsRequierd {
            get {
                return ResourceManager.GetString("IsAgreeTermsRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Requierd.
        /// </summary>
        public static string JobRequierd {
            get {
                return ResourceManager.GetString("JobRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Type Requierd.
        /// </summary>
        public static string JobTypeRequierd {
            get {
                return ResourceManager.GetString("JobTypeRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Address Requierd.
        /// </summary>
        public static string MainAddressRequierd {
            get {
                return ResourceManager.GetString("MainAddressRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Address Invlalid.
        /// </summary>
        public static string MainAddressValid {
            get {
                return ResourceManager.GetString("MainAddressValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Category Required.
        /// </summary>
        public static string MainCategoryRequired {
            get {
                return ResourceManager.GetString("MainCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page Required.
        /// </summary>
        public static string MainPageRequired {
            get {
                return ResourceManager.GetString("MainPageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Delivery Price Should Be Greater Than Zero.
        /// </summary>
        public static string MaxDeliveryPriceBiggerThanZero {
            get {
                return ResourceManager.GetString("MaxDeliveryPriceBiggerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxDelivery Price.
        /// </summary>
        public static string MaxDeliveryPriceRequired {
            get {
                return ResourceManager.GetString("MaxDeliveryPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Requierd.
        /// </summary>
        public static string MessageRequierd {
            get {
                return ResourceManager.GetString("MessageRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Delivery Price Should Be Greater Than Zero.
        /// </summary>
        public static string MinDeliveryPriceBiggerThanZero {
            get {
                return ResourceManager.GetString("MinDeliveryPriceBiggerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Delivery Price.
        /// </summary>
        public static string MinDeliveryPriceRequired {
            get {
                return ResourceManager.GetString("MinDeliveryPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Fare Required.
        /// </summary>
        public static string MinFareRequired {
            get {
                return ResourceManager.GetString("MinFareRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min KM Requierd.
        /// </summary>
        public static string MinKMRequierd {
            get {
                return ResourceManager.GetString("MinKMRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min KM Required.
        /// </summary>
        public static string MinKMRequired {
            get {
                return ResourceManager.GetString("MinKMRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Is Exists.
        /// </summary>
        public static string MobileIsExists {
            get {
                return ResourceManager.GetString("MobileIsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Requierd.
        /// </summary>
        public static string MobileRequierd {
            get {
                return ResourceManager.GetString("MobileRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No InValid.
        /// </summary>
        public static string MobileValid {
            get {
                return ResourceManager.GetString("MobileValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It must be greater than 0 .
        /// </summary>
        public static string NameMax0 {
            get {
                return ResourceManager.GetString("NameMax0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It must be lower than or equal to 10 characters.
        /// </summary>
        public static string NameMax10 {
            get {
                return ResourceManager.GetString("NameMax10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It must be lower than or equal to 100 characters.
        /// </summary>
        public static string NameMax100 {
            get {
                return ResourceManager.GetString("NameMax100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It must be lower than or equal to 15 characters.
        /// </summary>
        public static string NameMax15 {
            get {
                return ResourceManager.GetString("NameMax15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It must be lower than or equal to 20 characters.
        /// </summary>
        public static string NameMax20 {
            get {
                return ResourceManager.GetString("NameMax20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It must be lower than or equal to 300 characters.
        /// </summary>
        public static string NameMax300 {
            get {
                return ResourceManager.GetString("NameMax300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It must be lower than or equal to 4 characters.
        /// </summary>
        public static string NameMax4 {
            get {
                return ResourceManager.GetString("NameMax4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It must be lower than or equal to 50 characters.
        /// </summary>
        public static string NameMax50 {
            get {
                return ResourceManager.GetString("NameMax50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It must be lower than or equal to 75 characters.
        /// </summary>
        public static string NameMax75 {
            get {
                return ResourceManager.GetString("NameMax75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Requierd.
        /// </summary>
        public static string NameRequierd {
            get {
                return ResourceManager.GetString("NameRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality Requierd.
        /// </summary>
        public static string NationalityRequierd {
            get {
                return ResourceManager.GetString("NationalityRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value NotI dentical.
        /// </summary>
        public static string NotIdentical {
            get {
                return ResourceManager.GetString("NotIdentical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number must be 10.
        /// </summary>
        public static string number_must_be_10 {
            get {
                return ResourceManager.GetString("number_must_be_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers Only.
        /// </summary>
        public static string NumberOnly {
            get {
                return ResourceManager.GetString("NumberOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops this ID Number is found Before to a Captain account.
        /// </summary>
        public static string Oops_this_ID_Number_is_found_Before_to_a_Captain_account {
            get {
                return ResourceManager.GetString("Oops_this_ID_Number_is_found_Before_to_a_Captain_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Km Fare Requierd.
        /// </summary>
        public static string OverKmFareRequierd {
            get {
                return ResourceManager.GetString("OverKmFareRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must match.
        /// </summary>
        public static string Password_must_match {
            get {
                return ResourceManager.GetString("Password_must_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not match.
        /// </summary>
        public static string Password_not_match {
            get {
                return ResourceManager.GetString("Password_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Requierd.
        /// </summary>
        public static string PasswordRequierd {
            get {
                return ResourceManager.GetString("PasswordRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between 5 and 255 characters.
        /// </summary>
        public static string PasswordValidNumber {
            get {
                return ResourceManager.GetString("PasswordValidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Requierd.
        /// </summary>
        public static string PatientRequierd {
            get {
                return ResourceManager.GetString("PatientRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Requierd.
        /// </summary>
        public static string PercentRequierd {
            get {
                return ResourceManager.GetString("PercentRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No already exists.
        /// </summary>
        public static string Phone_Number_Is_Exists {
            get {
                return ResourceManager.GetString("Phone_Number_Is_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Requierd.
        /// </summary>
        public static string PhoneRequierd {
            get {
                return ResourceManager.GetString("PhoneRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Requierd.
        /// </summary>
        public static string PlaceRequierd {
            get {
                return ResourceManager.GetString("PlaceRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check Any Permission First.
        /// </summary>
        public static string Please_Check_Any_Permission_First {
            get {
                return ResourceManager.GetString("Please_Check_Any_Permission_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Requierd.
        /// </summary>
        public static string PositionRequierd {
            get {
                return ResourceManager.GetString("PositionRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Requierd.
        /// </summary>
        public static string PriceRequierd {
            get {
                return ResourceManager.GetString("PriceRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Required.
        /// </summary>
        public static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type Requierd.
        /// </summary>
        public static string ProductTypeRequierd {
            get {
                return ResourceManager.GetString("ProductTypeRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Requierd.
        /// </summary>
        public static string PromoRequierd {
            get {
                return ResourceManager.GetString("PromoRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Requierd.
        /// </summary>
        public static string QuestionRequierd {
            get {
                return ResourceManager.GetString("QuestionRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Requierd.
        /// </summary>
        public static string RegionRequierd {
            get {
                return ResourceManager.GetString("RegionRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requierd.
        /// </summary>
        public static string Requierd {
            get {
                return ResourceManager.GetString("Requierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string RequiredTxt {
            get {
                return ResourceManager.GetString("RequiredTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name Required.
        /// </summary>
        public static string SecondNameRequired {
            get {
                return ResourceManager.GetString("SecondNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SliderType Requierd.
        /// </summary>
        public static string SliderTypeRequierd {
            get {
                return ResourceManager.GetString("SliderTypeRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name Ar Requierd.
        /// </summary>
        public static string StoreNameAr {
            get {
                return ResourceManager.GetString("StoreNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name En Requierd.
        /// </summary>
        public static string StoreNameEn {
            get {
                return ResourceManager.GetString("StoreNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category Requierd.
        /// </summary>
        public static string SubCategoryRequierd {
            get {
                return ResourceManager.GetString("SubCategoryRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Ar required.
        /// </summary>
        public static string TitleArRequired {
            get {
                return ResourceManager.GetString("TitleArRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title En required.
        /// </summary>
        public static string TitleEnRequired {
            get {
                return ResourceManager.GetString("TitleEnRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Requierd.
        /// </summary>
        public static string TransactionTypeRequierd {
            get {
                return ResourceManager.GetString("TransactionTypeRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Is Exist.
        /// </summary>
        public static string User_Is_Exist {
            get {
                return ResourceManager.GetString("User_Is_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Requierd.
        /// </summary>
        public static string UserNameRequierd {
            get {
                return ResourceManager.GetString("UserNameRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Requierd.
        /// </summary>
        public static string VendorRequierd {
            get {
                return ResourceManager.GetString("VendorRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Requierd.
        /// </summary>
        public static string VoucherRequierd {
            get {
                return ResourceManager.GetString("VoucherRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Charge Required.
        /// </summary>
        public static string WaitingChargeRequired {
            get {
                return ResourceManager.GetString("WaitingChargeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Required.
        /// </summary>
        public static string WeightRequired {
            get {
                return ResourceManager.GetString("WeightRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Unit Required.
        /// </summary>
        public static string WeightUnitRequired {
            get {
                return ResourceManager.GetString("WeightUnitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Invalid.
        /// </summary>
        public static string YearInvalid {
            get {
                return ResourceManager.GetString("YearInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Requierd.
        /// </summary>
        public static string ZoneRequierd {
            get {
                return ResourceManager.GetString("ZoneRequierd", resourceCulture);
            }
        }
    }
}
