//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemade.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Response {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Response() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homemade.Api.Resources.Response", typeof(Response).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Financial penalty.
        /// </summary>
        public static string Add_Financial_penalty {
            get {
                return ResourceManager.GetString("Add_Financial_penalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Found.
        /// </summary>
        public static string Address_Found {
            get {
                return ResourceManager.GetString("Address Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because.
        /// </summary>
        public static string Because {
            get {
                return ResourceManager.GetString("Because", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Because Cancel Trip After Five Minutes.
        /// </summary>
        public static string Because_Cancel_Trip_After_Five_Minutes {
            get {
                return ResourceManager.GetString("Because_Cancel_Trip_After_Five_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Trip.
        /// </summary>
        public static string Cancel_Trip {
            get {
                return ResourceManager.GetString("Cancel_Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Trip By :.
        /// </summary>
        public static string Cancel_Trip_By {
            get {
                return ResourceManager.GetString("Cancel_Trip_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Create ==&gt; .
        /// </summary>
        public static string Cant_Create {
            get {
                return ResourceManager.GetString("Cant_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city ID not Found.
        /// </summary>
        public static string city_ID_not_Found {
            get {
                return ResourceManager.GetString("city_ID_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Token Not Valid.
        /// </summary>
        public static string Client_Token_Not_Valid {
            get {
                return ResourceManager.GetString("Client_Token_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color ID not Found.
        /// </summary>
        public static string Color_ID_not_Found {
            get {
                return ResourceManager.GetString("Color_ID_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country ID not Found.
        /// </summary>
        public static string Country_Req {
            get {
                return ResourceManager.GetString("Country_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data_Not_Found.
        /// </summary>
        public static string Data_Not_Found {
            get {
                return ResourceManager.GetString("Data_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Is Exist.
        /// </summary>
        public static string Email_Is_Exist {
            get {
                return ResourceManager.GetString("Email_Is_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Promo Code.
        /// </summary>
        public static string Enter_Promo_Code {
            get {
                return ResourceManager.GetString("Enter_Promo_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Valid Rate.
        /// </summary>
        public static string Enter_Valid_Rate {
            get {
                return ResourceManager.GetString("Enter_Valid_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Voucher Code.
        /// </summary>
        public static string Enter_Voucher_Code {
            get {
                return ResourceManager.GetString("Enter_Voucher_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error :.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Insert Evaluate.
        /// </summary>
        public static string Error_In_Insert_Evaluate {
            get {
                return ResourceManager.GetString("Error_In_Insert_Evaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Save Data.
        /// </summary>
        public static string Error_In_Save_Data {
            get {
                return ResourceManager.GetString("Error_In_Save_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Save Trip.
        /// </summary>
        public static string Error_In_Save_Trip {
            get {
                return ResourceManager.GetString("Error_In_Save_Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Seen Notification.
        /// </summary>
        public static string Error_In_Seen_Notification {
            get {
                return ResourceManager.GetString("Error_In_Seen_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ID error or does not have the authority to access here.
        /// </summary>
        public static string Error_in_the_client_username {
            get {
                return ResourceManager.GetString("Error_in_the_client_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in the Client&apos;s username.
        /// </summary>
        public static string Error_in_the_Clients_username {
            get {
                return ResourceManager.GetString("Error_in_the_Clients_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in the driver&apos;s username.
        /// </summary>
        public static string Error_in_the_drivers_username {
            get {
                return ResourceManager.GetString("Error_in_the_drivers_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Trip Id.
        /// </summary>
        public static string Error_In_Trip_Id {
            get {
                return ResourceManager.GetString("Error_In_Trip_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Update Trip.
        /// </summary>
        public static string Error_In_Update_Trip {
            get {
                return ResourceManager.GetString("Error_In_Update_Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In User Type.
        /// </summary>
        public static string Error_In_User_Type {
            get {
                return ResourceManager.GetString("Error_In_User_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when Create User Login Data. Check the Email And Mobile And Try Again.
        /// </summary>
        public static string Error_when_Create_User_Login_Data_Check_the_Email_And_Mobile_And_Try_Again {
            get {
                return ResourceManager.GetString("Error_when_Create_User_Login_Data_Check_the_Email_And_Mobile_And_Try_Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired promotional code.
        /// </summary>
        public static string Expired_promotional_code {
            get {
                return ResourceManager.GetString("Expired_promotional_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Trip Success.
        /// </summary>
        public static string Finish_Trip_Success {
            get {
                return ResourceManager.GetString("Finish_Trip_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id ExpieryDate not Found.
        /// </summary>
        public static string Id_ExpieryDate_not_Found {
            get {
                return ResourceManager.GetString("Id_ExpieryDate_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID No and Mobile No Not Found.
        /// </summary>
        public static string ID_No_and_Mobile_No_Not_Found {
            get {
                return ResourceManager.GetString("ID_No_and_Mobile_No_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id no must be 10 charcters.
        /// </summary>
        public static string id_no_must_be_10_charcters {
            get {
                return ResourceManager.GetString("id_no_must_be_10_charcters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID No not Found.
        /// </summary>
        public static string ID_No_not_Found {
            get {
                return ResourceManager.GetString("ID_No_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorrect Authorization Value.
        /// </summary>
        public static string incorrect_Authorization_Value {
            get {
                return ResourceManager.GetString("incorrect_Authorization_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error in the branch number or that it is not registered with us or this user does not have the authority to send from it.
        /// </summary>
        public static string Incorrect_branchId {
            get {
                return ResourceManager.GetString("Incorrect_branchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect receiver LocationId.
        /// </summary>
        public static string Incorrect_receiverLocationId {
            get {
                return ResourceManager.GetString("Incorrect_receiverLocationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid categoryCarTypeID ..!.
        /// </summary>
        public static string Invalid_categoryCarTypeID {
            get {
                return ResourceManager.GetString("Invalid_categoryCarTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid dropoffAddress ..!.
        /// </summary>
        public static string Invalid_dropoffAddress {
            get {
                return ResourceManager.GetString("Invalid_dropoffAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid dropoffLat ..!.
        /// </summary>
        public static string Invalid_dropoffLat {
            get {
                return ResourceManager.GetString("Invalid_dropoffLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid dropoffLng ..!.
        /// </summary>
        public static string Invalid_dropoffLng {
            get {
                return ResourceManager.GetString("Invalid_dropoffLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Lat Or Lng.
        /// </summary>
        public static string Invalid_LatLng {
            get {
                return ResourceManager.GetString("Invalid_LatLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone number.
        /// </summary>
        public static string Invalid_Phone_number {
            get {
                return ResourceManager.GetString("Invalid_Phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone number Stc.
        /// </summary>
        public static string Invalid_Phone_number_Stc {
            get {
                return ResourceManager.GetString("Invalid_Phone_number_Stc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pickAddress ..!.
        /// </summary>
        public static string Invalid_pickAddress {
            get {
                return ResourceManager.GetString("Invalid_pickAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pickupLat ..!.
        /// </summary>
        public static string Invalid_pickupLat {
            get {
                return ResourceManager.GetString("Invalid_pickupLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pickupLng ..!.
        /// </summary>
        public static string Invalid_pickupLng {
            get {
                return ResourceManager.GetString("Invalid_pickupLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Trip.
        /// </summary>
        public static string Invalid_Trip {
            get {
                return ResourceManager.GetString("Invalid_Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Trip Captains ..!.
        /// </summary>
        public static string Invalid_Trip_Drivers {
            get {
                return ResourceManager.GetString("Invalid_Trip_Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid trip ID ..!.
        /// </summary>
        public static string Invalid_trip_ID {
            get {
                return ResourceManager.GetString("Invalid_trip_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tripStatusId ..!.
        /// </summary>
        public static string Invalid_tripStatusId {
            get {
                return ResourceManager.GetString("Invalid_tripStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Successfuly.
        /// </summary>
        public static string Login_Successfuly {
            get {
                return ResourceManager.GetString("Login_Successfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Successfully.
        /// </summary>
        public static string Logout_Successfully {
            get {
                return ResourceManager.GetString("Logout_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxumim Limt Count.
        /// </summary>
        public static string Maxumim_Limt_Count {
            get {
                return ResourceManager.GetString("Maxumim_Limt_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No Is Exists.
        /// </summary>
        public static string Mobile_No_Is_Exists {
            get {
                return ResourceManager.GetString("Mobile_No_Is_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No not Found.
        /// </summary>
        public static string Mobile_No_not_Found {
            get {
                return ResourceManager.GetString("Mobile_No_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No Stc Is Exists.
        /// </summary>
        public static string Mobile_No_Stc_Is_Exists {
            get {
                return ResourceManager.GetString("Mobile_No_Stc_Is_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No Stc not Found.
        /// </summary>
        public static string Mobile_No_Stc_not_Found {
            get {
                return ResourceManager.GetString("Mobile_No_Stc_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to model ID not Found.
        /// </summary>
        public static string model_ID_not_Found {
            get {
                return ResourceManager.GetString("model_ID_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Is Exist.
        /// </summary>
        public static string Name_Is_Exist {
            get {
                return ResourceManager.GetString("Name_Is_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name not Found.
        /// </summary>
        public static string Name_not_Found {
            get {
                return ResourceManager.GetString("Name_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natonality is Requierd.
        /// </summary>
        public static string NationaltIsreq {
            get {
                return ResourceManager.GetString("NationaltIsreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string New_User {
            get {
                return ResourceManager.GetString("New_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Address Found.
        /// </summary>
        public static string No_Address_Found {
            get {
                return ResourceManager.GetString("No_Address_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found Picture.
        /// </summary>
        public static string Not_Found_Picture {
            get {
                return ResourceManager.GetString("Not_Found_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Valid Voucher Code.
        /// </summary>
        public static string Not_Valid_Voucher_Code {
            get {
                return ResourceManager.GetString("Not_Valid_Voucher_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your balance is not enough to receive the trips.
        /// </summary>
        public static string notAllowedMessage {
            get {
                return ResourceManager.GetString("notAllowedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops Error In Data.
        /// </summary>
        public static string Oops_Error_In_Data {
            get {
                return ResourceManager.GetString("Oops_Error_In_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops Seen Notification before.
        /// </summary>
        public static string Oops_Seen_Notification_before {
            get {
                return ResourceManager.GetString("Oops_Seen_Notification_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops this IdNo is found Before to a driver account.
        /// </summary>
        public static string Oops_this_IdNo_is_found_Before_to_a_driver_account {
            get {
                return ResourceManager.GetString("Oops_this_IdNo_is_found_Before_to_a_driver_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops this mobile no is found Before to a driver account.
        /// </summary>
        public static string Oops_this_mobile_no_is_found_Before_to_a_driver_account {
            get {
                return ResourceManager.GetString("Oops_this_mobile_no_is_found_Before_to_a_driver_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops this mobile no Stc is found Before to a driver account.
        /// </summary>
        public static string Oops_this_mobile_no_Stc_is_found_Before_to_a_driver_account {
            get {
                return ResourceManager.GetString("Oops_this_mobile_no_Stc_is_found_Before_to_a_driver_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops This Notification Not For PromoCode.
        /// </summary>
        public static string Oops_This_Notification_Not_For_Promo {
            get {
                return ResourceManager.GetString("Oops_This_Notification_Not_For_Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops this number is not Found.
        /// </summary>
        public static string Oops_this_number_is_not_Found {
            get {
                return ResourceManager.GetString("Oops_this_number_is_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops this number is not registered Before to a Client account.
        /// </summary>
        public static string Oops_this_number_is_not_registered_Before_to_a_Client_account {
            get {
                return ResourceManager.GetString("Oops_this_number_is_not_registered_Before_to_a_Client_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops this number is not registered Before to a Vendor account.
        /// </summary>
        public static string Oops_this_number_is_not_registered_Before_to_a_driver_account {
            get {
                return ResourceManager.GetString("Oops_this_number_is_not_registered_Before_to_a_driver_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops this number is registered Before to a Client account.
        /// </summary>
        public static string Oops_this_number_is_registered_Before_to_a_Client_account {
            get {
                return ResourceManager.GetString("Oops_this_number_is_registered_Before_to_a_Client_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops this number is registered Before to a Vendor account.
        /// </summary>
        public static string Oops_this_number_is_registered_Before_to_a_driver_account {
            get {
                return ResourceManager.GetString("Oops_this_number_is_registered_Before_to_a_driver_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops this Taxi Number is found Before.
        /// </summary>
        public static string Oops_this_Taxi_Number_is_found_Before {
            get {
                return ResourceManager.GetString("Oops_this_Taxi_Number_is_found_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be more than 5 digts.
        /// </summary>
        public static string Password_Not_Valid {
            get {
                return ResourceManager.GetString("Password_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Updated Failed.
        /// </summary>
        public static string Password_Updated_Failed {
            get {
                return ResourceManager.GetString("Password_Updated_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Updated Successfully.
        /// </summary>
        public static string Password_Updated_Successfully {
            get {
                return ResourceManager.GetString("Password_Updated_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment Status Not Valid.
        /// </summary>
        public static string paymentStatusNotValid {
            get {
                return ResourceManager.GetString("paymentStatusNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose Days Work.
        /// </summary>
        public static string Please_Choose_Days_Work {
            get {
                return ResourceManager.GetString("Please_Choose_Days_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Insert Data.
        /// </summary>
        public static string Please_Insert_Data {
            get {
                return ResourceManager.GetString("Please_Insert_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Insert Password.
        /// </summary>
        public static string Please_Insert_Password {
            get {
                return ResourceManager.GetString("Please_Insert_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Re Login.
        /// </summary>
        public static string Please_Re_Login {
            get {
                return ResourceManager.GetString("Please_Re_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again!.
        /// </summary>
        public static string Please_try_again {
            get {
                return ResourceManager.GetString("Please_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer not to specify.
        /// </summary>
        public static string Prefer_not_to_specify {
            get {
                return ResourceManager.GetString("Prefer_not_to_specify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated Added Successfully.
        /// </summary>
        public static string Rated_Added_Successfully {
            get {
                return ResourceManager.GetString("Rated_Added_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refrenceNumbers not found.
        /// </summary>
        public static string refrenceNumbers_not_found {
            get {
                return ResourceManager.GetString("refrenceNumbers_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Data Failed.
        /// </summary>
        public static string Return_Data_Failed {
            get {
                return ResourceManager.GetString("Return_Data_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Data Successfully.
        /// </summary>
        public static string Return_Data_Successfully {
            get {
                return ResourceManager.GetString("Return_Data_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Sucsess.
        /// </summary>
        public static string Save_Sucsess {
            get {
                return ResourceManager.GetString("Save_Sucsess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seen Notification Successfully.
        /// </summary>
        public static string Seen_Notification_Successfully {
            get {
                return ResourceManager.GetString("Seen_Notification_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry No Address Found.
        /// </summary>
        public static string Sorry_Address_Not_Found {
            get {
                return ResourceManager.GetString("Sorry_Address_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry Deleted Account.
        /// </summary>
        public static string Sorry_Deleted_Account {
            get {
                return ResourceManager.GetString("Sorry_Deleted_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry error in Trip Status.
        /// </summary>
        public static string Sorry_error_in_Trip_Status {
            get {
                return ResourceManager.GetString("Sorry_error_in_Trip_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry Not Allow Update.
        /// </summary>
        public static string Sorry_Not_Allow_Update {
            get {
                return ResourceManager.GetString("Sorry_Not_Allow_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , The Evaluation Has Aleardy been Done.
        /// </summary>
        public static string Sorry_The_Evaluation_Has_Aleardy_been_Done {
            get {
                return ResourceManager.GetString("Sorry_The_Evaluation_Has_Aleardy_been_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry This City is Out of Coverage.
        /// </summary>
        public static string Sorry_This_City_is_Out_of_Coverage {
            get {
                return ResourceManager.GetString("Sorry_This_City_is_Out_of_Coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry Trip Not Found.
        /// </summary>
        public static string Sorry_Trip_Not_Found {
            get {
                return ResourceManager.GetString("Sorry_Trip_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we are out of order now.
        /// </summary>
        public static string Sorry_we_are_out_of_order_now {
            get {
                return ResourceManager.GetString("Sorry_we_are_out_of_order_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry You Not Active.
        /// </summary>
        public static string Sorry_You_Not_Active {
            get {
                return ResourceManager.GetString("Sorry_You_Not_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry You Not Enable.
        /// </summary>
        public static string Sorry_You_Not_Enable {
            get {
                return ResourceManager.GetString("Sorry_You_Not_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Cancellation.
        /// </summary>
        public static string Tax_Cancellation {
            get {
                return ResourceManager.GetString("Tax_Cancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi No not Found.
        /// </summary>
        public static string Taxi_No_not_Found {
            get {
                return ResourceManager.GetString("Taxi_No_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for Registration,Your request has been send and we will contact with you soon..
        /// </summary>
        public static string Thanks_for_Registration_Your_request_has_been_send_and_we_will_contact_with_you_soon {
            get {
                return ResourceManager.GetString("Thanks_for_Registration_Your_request_has_been_send_and_we_will_contact_with_you_s" +
                        "oon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code was sent successfully.
        /// </summary>
        public static string The_code_was_sent_successfully {
            get {
                return ResourceManager.GetString("The_code_was_sent_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is now available.
        /// </summary>
        public static string The_service_is_now_available {
            get {
                return ResourceManager.GetString("The_service_is_now_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Trip was created successfully.
        /// </summary>
        public static string The_Trip_was_created_successfully {
            get {
                return ResourceManager.GetString("The_Trip_was_created_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Account Not Client.
        /// </summary>
        public static string This_Account_Not_Client {
            get {
                return ResourceManager.GetString("This_Account_Not_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Account Not Customer.
        /// </summary>
        public static string This_Account_Not_Customer {
            get {
                return ResourceManager.GetString("This_Account_Not_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Account Not Driver.
        /// </summary>
        public static string This_Account_Not_Driver {
            get {
                return ResourceManager.GetString("This_Account_Not_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Account Not Vendor.
        /// </summary>
        public static string This_Account_Not_Vendor {
            get {
                return ResourceManager.GetString("This_Account_Not_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Driver Not Exist.
        /// </summary>
        public static string This_Driver_Not_Exist {
            get {
                return ResourceManager.GetString("This_Driver_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This driver not valid on this trip.
        /// </summary>
        public static string This_driver_not_valid_on_this_trip {
            get {
                return ResourceManager.GetString("This_driver_not_valid_on_this_trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Driver Used This Voucher Before.
        /// </summary>
        public static string This_Driver_Used_This_Voucher_Before {
            get {
                return ResourceManager.GetString("This_Driver_Used_This_Voucher_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip ID Found Before.
        /// </summary>
        public static string Trip_ID_Found_Before {
            get {
                return ResourceManager.GetString("Trip_ID_Found_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip ID Order Is Incorrect.
        /// </summary>
        public static string Trip_ID_Order_Is_Incorrect {
            get {
                return ResourceManager.GetString("Trip_ID_Order_Is_Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Not Finshed yet.
        /// </summary>
        public static string Trip_Not_Finshed_yet {
            get {
                return ResourceManager.GetString("Trip_Not_Finshed_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Not Found,select the Trip And Try Again ..
        /// </summary>
        public static string Trip_Not_Found_select_the_Trip_And_Try_Again {
            get {
                return ResourceManager.GetString("Trip_Not_Found_select_the_Trip_And_Try_Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Status Type Not Correct.
        /// </summary>
        public static string Trip_Status_Type_Not_Correct {
            get {
                return ResourceManager.GetString("Trip_Status_Type_Not_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Updated Successfully.
        /// </summary>
        public static string TripUpdated {
            get {
                return ResourceManager.GetString("TripUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Should Be 1 or 2 only !.
        /// </summary>
        public static string Type_Should_Be_1_or_2_only {
            get {
                return ResourceManager.GetString("Type_Should_Be_1_or_2_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Success.
        /// </summary>
        public static string Update_Success {
            get {
                return ResourceManager.GetString("Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valid.
        /// </summary>
        public static string valid {
            get {
                return ResourceManager.GetString("valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Code is Expired.
        /// </summary>
        public static string Voucher_Code_is_Expired {
            get {
                return ResourceManager.GetString("Voucher_Code_is_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Old password.
        /// </summary>
        public static string Wrong_Old_password {
            get {
                return ResourceManager.GetString("Wrong_Old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password.
        /// </summary>
        public static string Wrong_username_or_password {
            get {
                return ResourceManager.GetString("Wrong_username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year ID not Found.
        /// </summary>
        public static string year_ID_not_Found {
            get {
                return ResourceManager.GetString("year_ID_not_Found", resourceCulture);
            }
        }
    }
}
