//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemade.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomemadeMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomemadeMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homemade.UI.Resources.HomemadeMenu", typeof(HomemadeMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string About_us {
            get {
                return ResourceManager.GetString("About_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Orders.
        /// </summary>
        public static string AcceptedOrders {
            get {
                return ResourceManager.GetString("AcceptedOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Requests.
        /// </summary>
        public static string Active_Requests {
            get {
                return ResourceManager.GetString("Active_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Request.
        /// </summary>
        public static string Active_Trip {
            get {
                return ResourceManager.GetString("Active_Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Admin.
        /// </summary>
        public static string Add_Admin {
            get {
                return ResourceManager.GetString("Add_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Appointment.
        /// </summary>
        public static string Add_Appointment {
            get {
                return ResourceManager.GetString("Add_Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Blocks.
        /// </summary>
        public static string Add_Blocks {
            get {
                return ResourceManager.GetString("Add_Blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Doctor.
        /// </summary>
        public static string Add_Doctor {
            get {
                return ResourceManager.GetString("Add_Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Employee.
        /// </summary>
        public static string Add_Employee {
            get {
                return ResourceManager.GetString("Add_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Branchs.
        /// </summary>
        public static string Add_New_Branchs {
            get {
                return ResourceManager.GetString("Add_New_Branchs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Employee.
        /// </summary>
        public static string Add_New_Employee {
            get {
                return ResourceManager.GetString("Add_New_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Product.
        /// </summary>
        public static string Add_New_Product {
            get {
                return ResourceManager.GetString("Add_New_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Staff.
        /// </summary>
        public static string Add_New_Staff {
            get {
                return ResourceManager.GetString("Add_New_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Vendor.
        /// </summary>
        public static string Add_New_Vend {
            get {
                return ResourceManager.GetString("Add_New_Vend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Vendor.
        /// </summary>
        public static string Add_New_Vendor {
            get {
                return ResourceManager.GetString("Add_New_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Branches.
        /// </summary>
        public static string AddBranches {
            get {
                return ResourceManager.GetString("AddBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Types.
        /// </summary>
        public static string AddressTypes {
            get {
                return ResourceManager.GetString("AddressTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shipping Company.
        /// </summary>
        public static string AddShippingCompany {
            get {
                return ResourceManager.GetString("AddShippingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Agent.
        /// </summary>
        public static string Agent_Add {
            get {
                return ResourceManager.GetString("Agent_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Report.
        /// </summary>
        public static string Agent_Report {
            get {
                return ResourceManager.GetString("Agent_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Reports.
        /// </summary>
        public static string Agent_Reports {
            get {
                return ResourceManager.GetString("Agent_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Agent.
        /// </summary>
        public static string Agent_Table {
            get {
                return ResourceManager.GetString("Agent_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agents.
        /// </summary>
        public static string Agents {
            get {
                return ResourceManager.GetString("Agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Diagnosis.
        /// </summary>
        public static string All_Diagnosis {
            get {
                return ResourceManager.GetString("All_Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        public static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Captains.
        /// </summary>
        public static string Assign_Captains {
            get {
                return ResourceManager.GetString("Assign_Captains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Captain Add.
        /// </summary>
        public static string Assign_Driver_Add {
            get {
                return ResourceManager.GetString("Assign_Driver_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Captain Table.
        /// </summary>
        public static string Assign_Driver_Table {
            get {
                return ResourceManager.GetString("Assign_Driver_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Order.
        /// </summary>
        public static string AssignOrder {
            get {
                return ResourceManager.GetString("AssignOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Verify.
        /// </summary>
        public static string Auto_Verify {
            get {
                return ResourceManager.GetString("Auto_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balances.
        /// </summary>
        public static string Balances {
            get {
                return ResourceManager.GetString("Balances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliders.
        /// </summary>
        public static string Banar {
            get {
                return ResourceManager.GetString("Banar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banks.
        /// </summary>
        public static string Banks {
            get {
                return ResourceManager.GetString("Banks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a Captain.
        /// </summary>
        public static string Become_a_Captain {
            get {
                return ResourceManager.GetString("Become_a_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a Partner.
        /// </summary>
        public static string Become_a_Partner {
            get {
                return ResourceManager.GetString("Become_a_Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Being Delivered Orders.
        /// </summary>
        public static string Being_DeliveredOrders {
            get {
                return ResourceManager.GetString("Being_DeliveredOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Being Processed Orders.
        /// </summary>
        public static string Being_ProcessedOrders {
            get {
                return ResourceManager.GetString("Being_ProcessedOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks.
        /// </summary>
        public static string Blocks {
            get {
                return ResourceManager.GetString("Blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branchs.
        /// </summary>
        public static string Branchs {
            get {
                return ResourceManager.GetString("Branchs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branchs History.
        /// </summary>
        public static string Branchs_History {
            get {
                return ResourceManager.GetString("Branchs_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Reason.
        /// </summary>
        public static string Cancel_Reason {
            get {
                return ResourceManager.GetString("Cancel_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Requests.
        /// </summary>
        public static string Cancel_Requests {
            get {
                return ResourceManager.GetString("Cancel_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled Orders.
        /// </summary>
        public static string CanceledOrders {
            get {
                return ResourceManager.GetString("CanceledOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        public static string Captain {
            get {
                return ResourceManager.GetString("Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain Register Request.
        /// </summary>
        public static string Captain_Reg {
            get {
                return ResourceManager.GetString("Captain_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain &amp; Taxis.
        /// </summary>
        public static string Captain_Taxis {
            get {
                return ResourceManager.GetString("Captain_Taxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain Blocks.
        /// </summary>
        public static string CaptainBlocks {
            get {
                return ResourceManager.GetString("CaptainBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captains.
        /// </summary>
        public static string Captains {
            get {
                return ResourceManager.GetString("Captains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain Zone.
        /// </summary>
        public static string CaptainZone {
            get {
                return ResourceManager.GetString("CaptainZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case List.
        /// </summary>
        public static string Case_List {
            get {
                return ResourceManager.GetString("Case_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches Finances.
        /// </summary>
        public static string Category_Fare {
            get {
                return ResourceManager.GetString("Category_Fare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Branch Finances.
        /// </summary>
        public static string Category_Fare_Add {
            get {
                return ResourceManager.GetString("Category_Fare_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches Finances Table.
        /// </summary>
        public static string Category_Fare_Table {
            get {
                return ResourceManager.GetString("Category_Fare_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certified Captain.
        /// </summary>
        public static string Certified_Captain {
            get {
                return ResourceManager.GetString("Certified_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities Covered.
        /// </summary>
        public static string CitiesCovered {
            get {
                return ResourceManager.GetString("CitiesCovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Balance.
        /// </summary>
        public static string Client_Balance {
            get {
                return ResourceManager.GetString("Client_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Balance Add.
        /// </summary>
        public static string Client_Balance_Add {
            get {
                return ResourceManager.GetString("Client_Balance_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Support.
        /// </summary>
        public static string Client_Support {
            get {
                return ResourceManager.GetString("Client_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Register Request.
        /// </summary>
        public static string Clients_Reg {
            get {
                return ResourceManager.GetString("Clients_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients Table.
        /// </summary>
        public static string Clients_Table {
            get {
                return ResourceManager.GetString("Clients_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect Invoice.
        /// </summary>
        public static string Collect_Invoice {
            get {
                return ResourceManager.GetString("Collect_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Companies .
        /// </summary>
        public static string Companies_List {
            get {
                return ResourceManager.GetString("Companies_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Finances.
        /// </summary>
        public static string Company_Finances {
            get {
                return ResourceManager.GetString("Company_Finances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Register Requests.
        /// </summary>
        public static string Company_Reg {
            get {
                return ResourceManager.GetString("Company_Reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Support.
        /// </summary>
        public static string Company_Support {
            get {
                return ResourceManager.GetString("Company_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Working Hours.
        /// </summary>
        public static string Company_Working_Hours {
            get {
                return ResourceManager.GetString("Company_Working_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Configration.
        /// </summary>
        public static string ConfigrationCompany {
            get {
                return ResourceManager.GetString("ConfigrationCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Contact_us {
            get {
                return ResourceManager.GetString("Contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converted.
        /// </summary>
        public static string Converted {
            get {
                return ResourceManager.GetString("Converted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Orders.
        /// </summary>
        public static string CreatedOrders {
            get {
                return ResourceManager.GetString("CreatedOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers Balance.
        /// </summary>
        public static string Customers_Balance {
            get {
                return ResourceManager.GetString("Customers_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers Details.
        /// </summary>
        public static string CustomersDetails {
            get {
                return ResourceManager.GetString("CustomersDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashBoard.
        /// </summary>
        public static string DashBoard {
            get {
                return ResourceManager.GetString("DashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered Requests.
        /// </summary>
        public static string Delivered_History {
            get {
                return ResourceManager.GetString("Delivered_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        public static string Delivered_History_2 {
            get {
                return ResourceManager.GetString("Delivered_History_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered Orders.
        /// </summary>
        public static string DeliveredOrders {
            get {
                return ResourceManager.GetString("DeliveredOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Invoice.
        /// </summary>
        public static string Delivery_Invoice {
            get {
                return ResourceManager.GetString("Delivery_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Setting.
        /// </summary>
        public static string Delivery_Setting {
            get {
                return ResourceManager.GetString("Delivery_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Type.
        /// </summary>
        public static string Delivery_Type {
            get {
                return ResourceManager.GetString("Delivery_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices Setting.
        /// </summary>
        public static string Devices_Setting {
            get {
                return ResourceManager.GetString("Devices_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis List.
        /// </summary>
        public static string Diagnosis_List {
            get {
                return ResourceManager.GetString("Diagnosis_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diseases.
        /// </summary>
        public static string Diseases {
            get {
                return ResourceManager.GetString("Diseases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diseases List.
        /// </summary>
        public static string Diseases_List {
            get {
                return ResourceManager.GetString("Diseases_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Managment.
        /// </summary>
        public static string Doctor_Managment {
            get {
                return ResourceManager.GetString("Doctor_Managment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        public static string Doctors {
            get {
                return ResourceManager.GetString("Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain Balance.
        /// </summary>
        public static string Driver_Balance {
            get {
                return ResourceManager.GetString("Driver_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain Report.
        /// </summary>
        public static string Driver_Report {
            get {
                return ResourceManager.GetString("Driver_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain Request Status.
        /// </summary>
        public static string Driver_Trip_Status {
            get {
                return ResourceManager.GetString("Driver_Trip_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain Interval.
        /// </summary>
        public static string DriverInterval {
            get {
                return ResourceManager.GetString("DriverInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captains.
        /// </summary>
        public static string Drivers {
            get {
                return ResourceManager.GetString("Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captains Help.
        /// </summary>
        public static string Drivers_Help {
            get {
                return ResourceManager.GetString("Drivers_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Support.
        /// </summary>
        public static string DriverSupport {
            get {
                return ResourceManager.GetString("DriverSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Appointment.
        /// </summary>
        public static string Edit_Appointment {
            get {
                return ResourceManager.GetString("Edit_Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Data.
        /// </summary>
        public static string Edit_Data {
            get {
                return ResourceManager.GetString("Edit_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enbale History.
        /// </summary>
        public static string EnbaleHistory {
            get {
                return ResourceManager.GetString("EnbaleHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitals.
        /// </summary>
        public static string Entities {
            get {
                return ResourceManager.GetString("Entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitals Group.
        /// </summary>
        public static string EntitiesGroup {
            get {
                return ResourceManager.GetString("EntitiesGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital Type.
        /// </summary>
        public static string EntityType {
            get {
                return ResourceManager.GetString("EntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Products.
        /// </summary>
        public static string Favourite_Products {
            get {
                return ResourceManager.GetString("Favourite_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Products.
        /// </summary>
        public static string FavouriteProducts {
            get {
                return ResourceManager.GetString("FavouriteProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files Types.
        /// </summary>
        public static string FilesTypes {
            get {
                return ResourceManager.GetString("FilesTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finances.
        /// </summary>
        public static string Finances {
            get {
                return ResourceManager.GetString("Finances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finances History.
        /// </summary>
        public static string Finances_History {
            get {
                return ResourceManager.GetString("Finances_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Setting.
        /// </summary>
        public static string General_Setting {
            get {
                return ResourceManager.GetString("General_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Invoice.
        /// </summary>
        public static string Generate_Invoice {
            get {
                return ResourceManager.GetString("Generate_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genetic Profile.
        /// </summary>
        public static string Genetic_Profile {
            get {
                return ResourceManager.GetString("Genetic_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Questions.
        /// </summary>
        public static string HelpQuestions {
            get {
                return ResourceManager.GetString("HelpQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Risk.
        /// </summary>
        public static string High_Risk {
            get {
                return ResourceManager.GetString("High_Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital Managment.
        /// </summary>
        public static string Hospital_Managment {
            get {
                return ResourceManager.GetString("Hospital_Managment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Orders.
        /// </summary>
        public static string Increase_Orders {
            get {
                return ResourceManager.GetString("Increase_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industy.
        /// </summary>
        public static string Industy {
            get {
                return ResourceManager.GetString("Industy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiries.
        /// </summary>
        public static string Inquiries {
            get {
                return ResourceManager.GetString("Inquiries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Report.
        /// </summary>
        public static string Invoice_Report {
            get {
                return ResourceManager.GetString("Invoice_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoices.
        /// </summary>
        public static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyWords.
        /// </summary>
        public static string KeyWords {
            get {
                return ResourceManager.GetString("KeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratory.
        /// </summary>
        public static string Laboratory {
            get {
                return ResourceManager.GetString("Laboratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Vendor - Productive families.
        /// </summary>
        public static string List_a_Vendors {
            get {
                return ResourceManager.GetString("List_a_Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Admins.
        /// </summary>
        public static string List_Admins {
            get {
                return ResourceManager.GetString("List_Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Captain Active.
        /// </summary>
        public static string List_Captain_Active {
            get {
                return ResourceManager.GetString("List_Captain_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Captain.
        /// </summary>
        public static string List_Captain_Taxis {
            get {
                return ResourceManager.GetString("List_Captain_Taxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Category Fare.
        /// </summary>
        public static string List_Category_Fare {
            get {
                return ResourceManager.GetString("List_Category_Fare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Client Balance.
        /// </summary>
        public static string List_Client_Balance {
            get {
                return ResourceManager.GetString("List_Client_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Collected.
        /// </summary>
        public static string List_Collected {
            get {
                return ResourceManager.GetString("List_Collected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Customers.
        /// </summary>
        public static string List_Customers {
            get {
                return ResourceManager.GetString("List_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Doctors.
        /// </summary>
        public static string List_Doctors {
            get {
                return ResourceManager.GetString("List_Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Captain Balance.
        /// </summary>
        public static string List_Driver_Balance {
            get {
                return ResourceManager.GetString("List_Driver_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Employees.
        /// </summary>
        public static string List_Employees {
            get {
                return ResourceManager.GetString("List_Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Hospitals.
        /// </summary>
        public static string List_Entities {
            get {
                return ResourceManager.GetString("List_Entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Operator.
        /// </summary>
        public static string List_Operator {
            get {
                return ResourceManager.GetString("List_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Patient.
        /// </summary>
        public static string List_Patient {
            get {
                return ResourceManager.GetString("List_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Products.
        /// </summary>
        public static string List_Products {
            get {
                return ResourceManager.GetString("List_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Promo Code.
        /// </summary>
        public static string List_Promo_Code {
            get {
                return ResourceManager.GetString("List_Promo_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Reward.
        /// </summary>
        public static string List_Reward {
            get {
                return ResourceManager.GetString("List_Reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Transfer.
        /// </summary>
        public static string List_Transfer {
            get {
                return ResourceManager.GetString("List_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Vendors.
        /// </summary>
        public static string List_Vendors {
            get {
                return ResourceManager.GetString("List_Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Voucher Code.
        /// </summary>
        public static string List_Voucher_Code {
            get {
                return ResourceManager.GetString("List_Voucher_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Category.
        /// </summary>
        public static string Main_Category {
            get {
                return ResourceManager.GetString("Main_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page Details.
        /// </summary>
        public static string MainPageDetails {
            get {
                return ResourceManager.GetString("MainPageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Pages.
        /// </summary>
        public static string MainPages {
            get {
                return ResourceManager.GetString("MainPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Mangment {
            get {
                return ResourceManager.GetString("Mangment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Administration.
        /// </summary>
        public static string Medical_Administration {
            get {
                return ResourceManager.GetString("Medical_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Managment.
        /// </summary>
        public static string Medical_Managment {
            get {
                return ResourceManager.GetString("Medical_Managment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicines.
        /// </summary>
        public static string Medicines {
            get {
                return ResourceManager.GetString("Medicines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medicines List.
        /// </summary>
        public static string Medicines_List {
            get {
                return ResourceManager.GetString("Medicines_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal Map.
        /// </summary>
        public static string Metal_Map {
            get {
                return ResourceManager.GetString("Metal_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tickets.
        /// </summary>
        public static string My_Ticket {
            get {
                return ResourceManager.GetString("My_Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Captain.
        /// </summary>
        public static string New_Captain {
            get {
                return ResourceManager.GetString("New_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Captain.
        /// </summary>
        public static string New_Captain_Taxis {
            get {
                return ResourceManager.GetString("New_Captain_Taxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Branches Finances.
        /// </summary>
        public static string New_Category_Fare {
            get {
                return ResourceManager.GetString("New_Category_Fare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Client.
        /// </summary>
        public static string New_Client {
            get {
                return ResourceManager.GetString("New_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Client Balance.
        /// </summary>
        public static string New_Client_Balance {
            get {
                return ResourceManager.GetString("New_Client_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Captain Balance.
        /// </summary>
        public static string New_Driver_Balance {
            get {
                return ResourceManager.GetString("New_Driver_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Hospital.
        /// </summary>
        public static string New_Entity {
            get {
                return ResourceManager.GetString("New_Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Operator.
        /// </summary>
        public static string New_Operator {
            get {
                return ResourceManager.GetString("New_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Patient.
        /// </summary>
        public static string New_Patient {
            get {
                return ResourceManager.GetString("New_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Product.
        /// </summary>
        public static string New_Product {
            get {
                return ResourceManager.GetString("New_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Promo Code.
        /// </summary>
        public static string New_Promo_Code {
            get {
                return ResourceManager.GetString("New_Promo_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Request.
        /// </summary>
        public static string New_Request {
            get {
                return ResourceManager.GetString("New_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Requests.
        /// </summary>
        public static string New_Requests {
            get {
                return ResourceManager.GetString("New_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Reward.
        /// </summary>
        public static string New_Reward {
            get {
                return ResourceManager.GetString("New_Reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Ticket.
        /// </summary>
        public static string New_Ticket {
            get {
                return ResourceManager.GetString("New_Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Voucher Code.
        /// </summary>
        public static string New_Voucher_Code {
            get {
                return ResourceManager.GetString("New_Voucher_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Accept Orders.
        /// </summary>
        public static string Not_Found {
            get {
                return ResourceManager.GetString("Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string OperationsNotFound {
            get {
                return ResourceManager.GetString("OperationsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators.
        /// </summary>
        public static string Operators {
            get {
                return ResourceManager.GetString("Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators Add.
        /// </summary>
        public static string Operators_Add {
            get {
                return ResourceManager.GetString("Operators_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operators Table.
        /// </summary>
        public static string Operators_Table {
            get {
                return ResourceManager.GetString("Operators_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Delivered.
        /// </summary>
        public static string Orders_Delivered {
            get {
                return ResourceManager.GetString("Orders_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders History.
        /// </summary>
        public static string Orders_History {
            get {
                return ResourceManager.GetString("Orders_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string Packages {
            get {
                return ResourceManager.GetString("Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Managment.
        /// </summary>
        public static string Patient_Managment {
            get {
                return ResourceManager.GetString("Patient_Managment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Configuration.
        /// </summary>
        public static string PaymentConfiguration {
            get {
                return ResourceManager.GetString("PaymentConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Reports.
        /// </summary>
        public static string PaymentReports {
            get {
                return ResourceManager.GetString("PaymentReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments Status.
        /// </summary>
        public static string PaymentsStatus {
            get {
                return ResourceManager.GetString("PaymentsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Ways.
        /// </summary>
        public static string PaymentWays {
            get {
                return ResourceManager.GetString("PaymentWays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Action.
        /// </summary>
        public static string Pending_Action {
            get {
                return ResourceManager.GetString("Pending_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Approve.
        /// </summary>
        public static string Pending_Approve {
            get {
                return ResourceManager.GetString("Pending_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Delivery Orders.
        /// </summary>
        public static string Pending_Delivery_Orders {
            get {
                return ResourceManager.GetString("Pending_Delivery_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Invoice.
        /// </summary>
        public static string Pending_Invoice {
            get {
                return ResourceManager.GetString("Pending_Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Requests.
        /// </summary>
        public static string Pending_Invoices {
            get {
                return ResourceManager.GetString("Pending_Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Requests.
        /// </summary>
        public static string Pending_Requests {
            get {
                return ResourceManager.GetString("Pending_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Transfer.
        /// </summary>
        public static string Pending_Transfer {
            get {
                return ResourceManager.GetString("Pending_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy.
        /// </summary>
        public static string Pharmacy {
            get {
                return ResourceManager.GetString("Pharmacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid from Logi Portal.
        /// </summary>
        public static string PortalPaid_History {
            get {
                return ResourceManager.GetString("PortalPaid_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string Processes {
            get {
                return ResourceManager.GetString("Processes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Requests.
        /// </summary>
        public static string Processing_Requests {
            get {
                return ResourceManager.GetString("Processing_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Code.
        /// </summary>
        public static string Promo_Code {
            get {
                return ResourceManager.GetString("Promo_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Code Add.
        /// </summary>
        public static string Promo_Code_Add {
            get {
                return ResourceManager.GetString("Promo_Code_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promo Code Table.
        /// </summary>
        public static string Promo_Code_Table {
            get {
                return ResourceManager.GetString("Promo_Code_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions And Ratings.
        /// </summary>
        public static string Questions_Ratings {
            get {
                return ResourceManager.GetString("Questions_Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        public static string Ratings {
            get {
                return ResourceManager.GetString("Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receivers.
        /// </summary>
        public static string Receivers {
            get {
                return ResourceManager.GetString("Receivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected Requests.
        /// </summary>
        public static string Rejected_Requests {
            get {
                return ResourceManager.GetString("Rejected_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports and Inquiries.
        /// </summary>
        public static string Reports_Inquiries {
            get {
                return ResourceManager.GetString("Reports_Inquiries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests History.
        /// </summary>
        public static string Requests_History {
            get {
                return ResourceManager.GetString("Requests_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward.
        /// </summary>
        public static string Reward {
            get {
                return ResourceManager.GetString("Reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Configration.
        /// </summary>
        public static string Role_Configration {
            get {
                return ResourceManager.GetString("Role_Configration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Permissions.
        /// </summary>
        public static string Role_Permissions {
            get {
                return ResourceManager.GetString("Role_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Orders.
        /// </summary>
        public static string Schedule_Orders {
            get {
                return ResourceManager.GetString("Schedule_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Requests.
        /// </summary>
        public static string Schedule_Requests {
            get {
                return ResourceManager.GetString("Schedule_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string Send_Message {
            get {
                return ResourceManager.GetString("Send_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Ticket.
        /// </summary>
        public static string Sent_Ticket {
            get {
                return ResourceManager.GetString("Sent_Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Providers.
        /// </summary>
        public static string Service_Providers {
            get {
                return ResourceManager.GetString("Service_Providers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Companies.
        /// </summary>
        public static string ShippingCompanies {
            get {
                return ResourceManager.GetString("ShippingCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Company.
        /// </summary>
        public static string ShippingCompany {
            get {
                return ResourceManager.GetString("ShippingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Orders.
        /// </summary>
        public static string ShippingOrders {
            get {
                return ResourceManager.GetString("ShippingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sliders.
        /// </summary>
        public static string Sliders {
            get {
                return ResourceManager.GetString("Sliders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Permissions.
        /// </summary>
        public static string Staff_Permissions {
            get {
                return ResourceManager.GetString("Staff_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches Roles.
        /// </summary>
        public static string Staff_Roles {
            get {
                return ResourceManager.GetString("Staff_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to staffs History.
        /// </summary>
        public static string staffs_History {
            get {
                return ResourceManager.GetString("staffs_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Category.
        /// </summary>
        public static string Sub_Category {
            get {
                return ResourceManager.GetString("Sub_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions Email.
        /// </summary>
        public static string Subscriptions_Email {
            get {
                return ResourceManager.GetString("Subscriptions_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Admin.
        /// </summary>
        public static string System_Admin {
            get {
                return ResourceManager.GetString("System_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Administrators.
        /// </summary>
        public static string System_Administrators {
            get {
                return ResourceManager.GetString("System_Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Employees.
        /// </summary>
        public static string System_Employees {
            get {
                return ResourceManager.GetString("System_Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Managment.
        /// </summary>
        public static string System_Managment {
            get {
                return ResourceManager.GetString("System_Managment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi Report.
        /// </summary>
        public static string Taxi_Report {
            get {
                return ResourceManager.GetString("Taxi_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxis.
        /// </summary>
        public static string Taxis {
            get {
                return ResourceManager.GetString("Taxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets.
        /// </summary>
        public static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Orders.
        /// </summary>
        public static string TrackingOrders {
            get {
                return ResourceManager.GetString("TrackingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        public static string Transaction_Type {
            get {
                return ResourceManager.GetString("Transaction_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Finanical.
        /// </summary>
        public static string Trip_Finanical {
            get {
                return ResourceManager.GetString("Trip_Finanical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request History.
        /// </summary>
        public static string Trip_History {
            get {
                return ResourceManager.GetString("Trip_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Promo.
        /// </summary>
        public static string Trip_Promo {
            get {
                return ResourceManager.GetString("Trip_Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status.
        /// </summary>
        public static string Trip_Status {
            get {
                return ResourceManager.GetString("Trip_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Trips {
            get {
                return ResourceManager.GetString("Trips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Observation.
        /// </summary>
        public static string Under_Observation {
            get {
                return ResourceManager.GetString("Under_Observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Scrutiny.
        /// </summary>
        public static string UnderScrutiny {
            get {
                return ResourceManager.GetString("UnderScrutiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Assigns.
        /// </summary>
        public static string Update_Assigns {
            get {
                return ResourceManager.GetString("Update_Assigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Blocks.
        /// </summary>
        public static string Update_Blocks {
            get {
                return ResourceManager.GetString("Update_Blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User in Role.
        /// </summary>
        public static string Users_In_Role {
            get {
                return ResourceManager.GetString("Users_In_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaccations History.
        /// </summary>
        public static string VacHistory {
            get {
                return ResourceManager.GetString("VacHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        public static string Vendors {
            get {
                return ResourceManager.GetString("Vendors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Appointment.
        /// </summary>
        public static string View_Appointment {
            get {
                return ResourceManager.GetString("View_Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Appointments.
        /// </summary>
        public static string View_Appointments {
            get {
                return ResourceManager.GetString("View_Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        public static string Visits {
            get {
                return ResourceManager.GetString("Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Add.
        /// </summary>
        public static string Voucher_Add {
            get {
                return ResourceManager.GetString("Voucher_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Code.
        /// </summary>
        public static string Voucher_Code {
            get {
                return ResourceManager.GetString("Voucher_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Captain.
        /// </summary>
        public static string Voucher_Driver {
            get {
                return ResourceManager.GetString("Voucher_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Table.
        /// </summary>
        public static string Voucher_Table {
            get {
                return ResourceManager.GetString("Voucher_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting Activation.
        /// </summary>
        public static string Waiting_Activation {
            get {
                return ResourceManager.GetString("Waiting_Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Type.
        /// </summary>
        public static string Work_Type {
            get {
                return ResourceManager.GetString("Work_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
