//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homemade.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Response_ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Response_ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Homemade.UI.Resources.Response-ar", typeof(Response_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم وضع غرامة مالية.
        /// </summary>
        public static string Add_Financial_penalty {
            get {
                return ResourceManager.GetString("Add_Financial_penalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسبب.
        /// </summary>
        public static string Because {
            get {
                return ResourceManager.GetString("Because", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسبب إلغاء الرحلة بعد 5 دقائق من انشائها.
        /// </summary>
        public static string Because_Cancel_Trip_After_Five_Minutes {
            get {
                return ResourceManager.GetString("Because_Cancel_Trip_After_Five_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الغاء الرحلة.
        /// </summary>
        public static string Cancel_Trip {
            get {
                return ResourceManager.GetString("Cancel_Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الغاء الرحلة من قبل :.
        /// </summary>
        public static string Cancel_Trip_By {
            get {
                return ResourceManager.GetString("Cancel_Trip_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايمكن التسجيل  ==&gt; .
        /// </summary>
        public static string Cant_Create {
            get {
                return ResourceManager.GetString("Cant_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم اختيار المدينة.
        /// </summary>
        public static string city_ID_not_Found {
            get {
                return ResourceManager.GetString("city_ID_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في هوية الراكب.
        /// </summary>
        public static string Client_Token_Not_Valid {
            get {
                return ResourceManager.GetString("Client_Token_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم اختيار اللون.
        /// </summary>
        public static string Color_ID_not_Found {
            get {
                return ResourceManager.GetString("Color_ID_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البلد غير محددة.
        /// </summary>
        public static string Country_Req {
            get {
                return ResourceManager.GetString("Country_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد بيانات.
        /// </summary>
        public static string Data_Not_Found {
            get {
                return ResourceManager.GetString("Data_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكترونى موجود بالفعل.
        /// </summary>
        public static string Email_Is_Exist {
            get {
                return ResourceManager.GetString("Email_Is_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل الرمز الترويجي.
        /// </summary>
        public static string Enter_Promo_Code {
            get {
                return ResourceManager.GetString("Enter_Promo_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل تقييم صحيح.
        /// </summary>
        public static string Enter_Valid_Rate {
            get {
                return ResourceManager.GetString("Enter_Valid_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال كود إذن الصرف.
        /// </summary>
        public static string Enter_Voucher_Code {
            get {
                return ResourceManager.GetString("Enter_Voucher_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ :.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا في إضافة التقييم.
        /// </summary>
        public static string Error_In_Insert_Evaluate {
            get {
                return ResourceManager.GetString("Error_In_Insert_Evaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ فى حفظ البيانات.
        /// </summary>
        public static string Error_In_Save_Data {
            get {
                return ResourceManager.GetString("Error_In_Save_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ فى حفظ الرحلة.
        /// </summary>
        public static string Error_In_Save_Trip {
            get {
                return ResourceManager.GetString("Error_In_Save_Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل فى قراءة الاشعار.
        /// </summary>
        public static string Error_In_Seen_Notification {
            get {
                return ResourceManager.GetString("Error_In_Seen_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ فى معرف دخلو المتجر او ليس له صلاحيه للوصل لهذا.
        /// </summary>
        public static string Error_in_the_client_username {
            get {
                return ResourceManager.GetString("Error_in_the_client_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا فى اسم المستخدم الخاص بالراكب.
        /// </summary>
        public static string Error_in_the_Clients_username {
            get {
                return ResourceManager.GetString("Error_in_the_Clients_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا فى اسم المستخدم الخاص بالسائق.
        /// </summary>
        public static string Error_in_the_drivers_username {
            get {
                return ResourceManager.GetString("Error_in_the_drivers_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ فى رقم الرحلة.
        /// </summary>
        public static string Error_In_Trip_Id {
            get {
                return ResourceManager.GetString("Error_In_Trip_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في تعديل بيانات الرحلة.
        /// </summary>
        public static string Error_In_Update_Trip {
            get {
                return ResourceManager.GetString("Error_In_Update_Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ فى نوع المستخدم.
        /// </summary>
        public static string Error_In_User_Type {
            get {
                return ResourceManager.GetString("Error_In_User_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ عند إنشاء بيانات تسجيل دخول المستخدم. التحقق من البريد الإلكتروني والجوال وحاول مرة أخرى.
        /// </summary>
        public static string Error_when_Create_User_Login_Data_Check_the_Email_And_Mobile_And_Try_Again {
            get {
                return ResourceManager.GetString("Error_when_Create_User_Login_Data_Check_the_Email_And_Mobile_And_Try_Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز ترويجي منتهي الصلاحية.
        /// </summary>
        public static string Expired_promotional_code {
            get {
                return ResourceManager.GetString("Expired_promotional_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انثى.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انهاء الرحلة بنجاح.
        /// </summary>
        public static string Finish_Trip_Success {
            get {
                return ResourceManager.GetString("Finish_Trip_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ إنتهاء الهوية غير موجود.
        /// </summary>
        public static string Id_ExpieryDate_not_Found {
            get {
                return ResourceManager.GetString("Id_ExpieryDate_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية ورقم الجوال غير موجودين.
        /// </summary>
        public static string ID_No_and_Mobile_No_Not_Found {
            get {
                return ResourceManager.GetString("ID_No_and_Mobile_No_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية يجب ان يكون مكون من 10 أرقام.
        /// </summary>
        public static string id_no_must_be_10_charcters {
            get {
                return ResourceManager.GetString("id_no_must_be_10_charcters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية غير موجود.
        /// </summary>
        public static string ID_No_not_Found {
            get {
                return ResourceManager.GetString("ID_No_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمة التوكين غير صحيحة.
        /// </summary>
        public static string incorrect_Authorization_Value {
            get {
                return ResourceManager.GetString("incorrect_Authorization_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ فى رقم الفرع او انه غير مسجل لدينا او هذا المستخدم ليس له صلاحيه للاسال منه.
        /// </summary>
        public static string Incorrect_branchId {
            get {
                return ResourceManager.GetString("Incorrect_branchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا فى رقم موقع العميل.
        /// </summary>
        public static string Incorrect_receiverLocationId {
            get {
                return ResourceManager.GetString("Incorrect_receiverLocationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ كود نوع الفئة.
        /// </summary>
        public static string Invalid_categoryCarTypeID {
            get {
                return ResourceManager.GetString("Invalid_categoryCarTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ عنوان الوصول.
        /// </summary>
        public static string Invalid_dropoffAddress {
            get {
                return ResourceManager.GetString("Invalid_dropoffAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ لات الوصول.
        /// </summary>
        public static string Invalid_dropoffLat {
            get {
                return ResourceManager.GetString("Invalid_dropoffLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ لانج الوصول.
        /// </summary>
        public static string Invalid_dropoffLng {
            get {
                return ResourceManager.GetString("Invalid_dropoffLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ فى احداثيات خط الطول او العرض.
        /// </summary>
        public static string Invalid_LatLng {
            get {
                return ResourceManager.GetString("Invalid_LatLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال غير صالح.
        /// </summary>
        public static string Invalid_Phone_number {
            get {
                return ResourceManager.GetString("Invalid_Phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ فى رقم الجوال Stc.
        /// </summary>
        public static string Invalid_Phone_number_Stc {
            get {
                return ResourceManager.GetString("Invalid_Phone_number_Stc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ عنوان الالتقاط.
        /// </summary>
        public static string Invalid_pickAddress {
            get {
                return ResourceManager.GetString("Invalid_pickAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ لات الالتقاط.
        /// </summary>
        public static string Invalid_pickupLat {
            get {
                return ResourceManager.GetString("Invalid_pickupLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ لانج الالتقاط.
        /// </summary>
        public static string Invalid_pickupLng {
            get {
                return ResourceManager.GetString("Invalid_pickupLng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رحله غير مسجله.
        /// </summary>
        public static string Invalid_Trip {
            get {
                return ResourceManager.GetString("Invalid_Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ سائقين الرحلة.
        /// </summary>
        public static string Invalid_Trip_Drivers {
            get {
                return ResourceManager.GetString("Invalid_Trip_Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ كود الرحلة.
        /// </summary>
        public static string Invalid_trip_ID {
            get {
                return ResourceManager.GetString("Invalid_trip_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ كود حالة الرحلة.
        /// </summary>
        public static string Invalid_tripStatusId {
            get {
                return ResourceManager.GetString("Invalid_tripStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الدخول بنجاح.
        /// </summary>
        public static string Login_Successfuly {
            get {
                return ResourceManager.GetString("Login_Successfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الخروج بنجاح.
        /// </summary>
        public static string Logout_Successfully {
            get {
                return ResourceManager.GetString("Logout_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انتهاء العدد الخاص بالرمز.
        /// </summary>
        public static string Maxumim_Limt_Count {
            get {
                return ResourceManager.GetString("Maxumim_Limt_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا رقم الجوال مسجل بالفعل.
        /// </summary>
        public static string Mobile_No_Is_Exists {
            get {
                return ResourceManager.GetString("Mobile_No_Is_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال غير موجود.
        /// </summary>
        public static string Mobile_No_not_Found {
            get {
                return ResourceManager.GetString("Mobile_No_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال Stc موجود بالفعل.
        /// </summary>
        public static string Mobile_No_Stc_Is_Exists {
            get {
                return ResourceManager.GetString("Mobile_No_Stc_Is_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال stc غير موجود.
        /// </summary>
        public static string Mobile_No_Stc_not_Found {
            get {
                return ResourceManager.GetString("Mobile_No_Stc_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم اختيار نوع المركبة.
        /// </summary>
        public static string model_ID_not_Found {
            get {
                return ResourceManager.GetString("model_ID_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم موجود بالفعل.
        /// </summary>
        public static string Name_Is_Exist {
            get {
                return ResourceManager.GetString("Name_Is_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسم غير موجود.
        /// </summary>
        public static string Name_not_Found {
            get {
                return ResourceManager.GetString("Name_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية مطلوبة.
        /// </summary>
        public static string NationaltIsreq {
            get {
                return ResourceManager.GetString("NationaltIsreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم جديد.
        /// </summary>
        public static string New_User {
            get {
                return ResourceManager.GetString("New_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ لا يوجد صورة.
        /// </summary>
        public static string Not_Found_Picture {
            get {
                return ResourceManager.GetString("Not_Found_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود إذن صرف غير صالح.
        /// </summary>
        public static string Not_Valid_Voucher_Code {
            get {
                return ResourceManager.GetString("Not_Valid_Voucher_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رصيدك غير كافي لإستقبال الرحلات.
        /// </summary>
        public static string notAllowedMessage {
            get {
                return ResourceManager.GetString("notAllowedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا خطأ فى البيانات.
        /// </summary>
        public static string Oops_Error_In_Data {
            get {
                return ResourceManager.GetString("Oops_Error_In_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا تم القراءة من قبل.
        /// </summary>
        public static string Oops_Seen_Notification_before {
            get {
                return ResourceManager.GetString("Oops_Seen_Notification_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا هذا رقم الهوية موجود من قبل لحساب سائق.
        /// </summary>
        public static string Oops_this_IdNo_is_found_Before_to_a_driver_account {
            get {
                return ResourceManager.GetString("Oops_this_IdNo_is_found_Before_to_a_driver_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا رقم الجوال موجود من قبل لحساب تاجر.
        /// </summary>
        public static string Oops_this_mobile_no_is_found_Before_to_a_driver_account {
            get {
                return ResourceManager.GetString("Oops_this_mobile_no_is_found_Before_to_a_driver_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا رقم الجوال stc موجود من قبل لحساب سائق.
        /// </summary>
        public static string Oops_this_mobile_no_Stc_is_found_Before_to_a_driver_account {
            get {
                return ResourceManager.GetString("Oops_this_mobile_no_Stc_is_found_Before_to_a_driver_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ هذا الاشعار ليس للخصم.
        /// </summary>
        public static string Oops_This_Notification_Not_For_Promo {
            get {
                return ResourceManager.GetString("Oops_This_Notification_Not_For_Promo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الرقم غير موجود.
        /// </summary>
        public static string Oops_this_number_is_not_Found {
            get {
                return ResourceManager.GetString("Oops_this_number_is_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا هذا الرقم غير مسجل من قبل لحساب الراكب.
        /// </summary>
        public static string Oops_this_number_is_not_registered_Before_to_a_Client_account {
            get {
                return ResourceManager.GetString("Oops_this_number_is_not_registered_Before_to_a_Client_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا هذا الرقم غير مسجل من قبل لحساب سائق.
        /// </summary>
        public static string Oops_this_number_is_not_registered_Before_to_a_driver_account {
            get {
                return ResourceManager.GetString("Oops_this_number_is_not_registered_Before_to_a_driver_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا هذا الرقم مسجل من قبل لحساب راكب.
        /// </summary>
        public static string Oops_this_number_is_registered_Before_to_a_Client_account {
            get {
                return ResourceManager.GetString("Oops_this_number_is_registered_Before_to_a_Client_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا هذا الرقم مسجل من قبل لحساب سائق.
        /// </summary>
        public static string Oops_this_number_is_registered_Before_to_a_driver_account {
            get {
                return ResourceManager.GetString("Oops_this_number_is_registered_Before_to_a_driver_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا هذا رقم السيارة موجود من قبل.
        /// </summary>
        public static string Oops_this_Taxi_Number_is_found_Before {
            get {
                return ResourceManager.GetString("Oops_this_Taxi_Number_is_found_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ فى كلمة المرور.
        /// </summary>
        public static string Password_Not_Valid {
            get {
                return ResourceManager.GetString("Password_Not_Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل فى تعديل كلمة المرور.
        /// </summary>
        public static string Password_Updated_Failed {
            get {
                return ResourceManager.GetString("Password_Updated_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل كلمة المرور بنجاح.
        /// </summary>
        public static string Password_Updated_Successfully {
            get {
                return ResourceManager.GetString("Password_Updated_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الدفع غير متواجدة.
        /// </summary>
        public static string paymentStatusNotValid {
            get {
                return ResourceManager.GetString("paymentStatusNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال البيانات.
        /// </summary>
        public static string Please_Insert_Data {
            get {
                return ResourceManager.GetString("Please_Insert_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء ادخال كلمة المرور.
        /// </summary>
        public static string Please_Insert_Password {
            get {
                return ResourceManager.GetString("Please_Insert_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك سجل الدخول مره اخرى.
        /// </summary>
        public static string Please_Re_Login {
            get {
                return ResourceManager.GetString("Please_Re_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فضلا اعد المحاولة مرة اخرى.
        /// </summary>
        public static string Please_try_again {
            get {
                return ResourceManager.GetString("Please_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يفضل عدم التحديد.
        /// </summary>
        public static string Prefer_not_to_specify {
            get {
                return ResourceManager.GetString("Prefer_not_to_specify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم التقييم بنجاح.
        /// </summary>
        public static string Rated_Added_Successfully {
            get {
                return ResourceManager.GetString("Rated_Added_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الارقام المرعية غير موجودة.
        /// </summary>
        public static string refrenceNumbers_not_found {
            get {
                return ResourceManager.GetString("refrenceNumbers_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل ارجاع البيانات.
        /// </summary>
        public static string Return_Data_Failed {
            get {
                return ResourceManager.GetString("Return_Data_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم ارجاع البيانات بنجاح.
        /// </summary>
        public static string Return_Data_Successfully {
            get {
                return ResourceManager.GetString("Return_Data_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        public static string Save_Sucsess {
            get {
                return ResourceManager.GetString("Save_Sucsess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم قراءة الاشعار بنجاح.
        /// </summary>
        public static string Seen_Notification_Successfully {
            get {
                return ResourceManager.GetString("Seen_Notification_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد اى عنوان لهذا الرقم.
        /// </summary>
        public static string Sorry_Address_Not_Found {
            get {
                return ResourceManager.GetString("Sorry_Address_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا خطأ فى حالة الرحلة.
        /// </summary>
        public static string Sorry_error_in_Trip_Status {
            get {
                return ResourceManager.GetString("Sorry_error_in_Trip_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا لا يمكنك التعديل.
        /// </summary>
        public static string Sorry_Not_Allow_Update {
            get {
                return ResourceManager.GetString("Sorry_Not_Allow_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا لقد تم التقييم مسبقا.
        /// </summary>
        public static string Sorry_The_Evaluation_Has_Aleardy_been_Done {
            get {
                return ResourceManager.GetString("Sorry_The_Evaluation_Has_Aleardy_been_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا هذه المدينة خارج التغطية.
        /// </summary>
        public static string Sorry_This_City_is_Out_of_Coverage {
            get {
                return ResourceManager.GetString("Sorry_This_City_is_Out_of_Coverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا في الرحلة.
        /// </summary>
        public static string Sorry_Trip_Not_Found {
            get {
                return ResourceManager.GetString("Sorry_Trip_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا لم يتم تفعيلك بعد.
        /// </summary>
        public static string Sorry_You_Not_Active {
            get {
                return ResourceManager.GetString("Sorry_You_Not_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا ليس لديك صلاحية العمل.
        /// </summary>
        public static string Sorry_You_Not_Enable {
            get {
                return ResourceManager.GetString("Sorry_You_Not_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضريبة الغاء.
        /// </summary>
        public static string Tax_Cancellation {
            get {
                return ResourceManager.GetString("Tax_Cancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم السيارة غير موجود.
        /// </summary>
        public static string Taxi_No_not_Found {
            get {
                return ResourceManager.GetString("Taxi_No_not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شكرا لتسجليكم، تم ارسال طلب الاشتراك بنجاح وسيتم التوصيل معكم في أقرب وقت..
        /// </summary>
        public static string Thanks_for_Registration_Your_request_has_been_send_and_we_will_contact_with_you_soon {
            get {
                return ResourceManager.GetString("Thanks_for_Registration_Your_request_has_been_send_and_we_will_contact_with_you_s" +
                        "oon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم ارسال الكود بتجاح.
        /// </summary>
        public static string The_code_was_sent_successfully {
            get {
                return ResourceManager.GetString("The_code_was_sent_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم انشاء الرحله بنجاح.
        /// </summary>
        public static string The_Trip_was_created_successfully {
            get {
                return ResourceManager.GetString("The_Trip_was_created_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحساب غير خاص براكب.
        /// </summary>
        public static string This_Account_Not_Client {
            get {
                return ResourceManager.GetString("This_Account_Not_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحساب غير خاص بعميل.
        /// </summary>
        public static string This_Account_Not_Customer {
            get {
                return ResourceManager.GetString("This_Account_Not_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحساب غير خاص بسائق.
        /// </summary>
        public static string This_Account_Not_Driver {
            get {
                return ResourceManager.GetString("This_Account_Not_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحساب غير خاص ببائع.
        /// </summary>
        public static string This_Account_Not_Vendor {
            get {
                return ResourceManager.GetString("This_Account_Not_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا السائق غير موجود.
        /// </summary>
        public static string This_Driver_Not_Exist {
            get {
                return ResourceManager.GetString("This_Driver_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا هذا السائق غير مسجل علي هذه الرحلة.
        /// </summary>
        public static string This_driver_not_valid_on_this_trip {
            get {
                return ResourceManager.GetString("This_driver_not_valid_on_this_trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا السائق مستخدم هذه القسيمة من قبل.
        /// </summary>
        public static string This_Driver_Used_This_Voucher_Before {
            get {
                return ResourceManager.GetString("This_Driver_Used_This_Voucher_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الرحلة موجود من قبل.
        /// </summary>
        public static string Trip_ID_Found_Before {
            get {
                return ResourceManager.GetString("Trip_ID_Found_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتيب رقم الرحلة غير صحيح.
        /// </summary>
        public static string Trip_ID_Order_Is_Incorrect {
            get {
                return ResourceManager.GetString("Trip_ID_Order_Is_Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرحلة لم تنتهي بعد.
        /// </summary>
        public static string Trip_Not_Finshed_yet {
            get {
                return ResourceManager.GetString("Trip_Not_Finshed_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على الرحلة ، حدد الرحلة وحاول مرة أخرى..
        /// </summary>
        public static string Trip_Not_Found_select_the_Trip_And_Try_Again {
            get {
                return ResourceManager.GetString("Trip_Not_Found_select_the_Trip_And_Try_Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حاله الرحله غير صحيحه.
        /// </summary>
        public static string Trip_Status_Type_Not_Correct {
            get {
                return ResourceManager.GetString("Trip_Status_Type_Not_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعديل الرحلة بنجاح.
        /// </summary>
        public static string TripUpdated {
            get {
                return ResourceManager.GetString("TripUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع يجب ان يكون 1 او 2 فقط.
        /// </summary>
        public static string Type_Should_Be_1_or_2_only {
            get {
                return ResourceManager.GetString("Type_Should_Be_1_or_2_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التحديث بنجاح.
        /// </summary>
        public static string Update_Success {
            get {
                return ResourceManager.GetString("Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صحيح.
        /// </summary>
        public static string valid {
            get {
                return ResourceManager.GetString("valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز القسيمة منتهى.
        /// </summary>
        public static string Voucher_Code_is_Expired {
            get {
                return ResourceManager.GetString("Voucher_Code_is_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ فى كلمة المرور القديمة.
        /// </summary>
        public static string Wrong_Old_password {
            get {
                return ResourceManager.GetString("Wrong_Old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم او كلمة المرور خطأ.
        /// </summary>
        public static string Wrong_username_or_password {
            get {
                return ResourceManager.GetString("Wrong_username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم اختيار الموديل.
        /// </summary>
        public static string year_ID_not_Found {
            get {
                return ResourceManager.GetString("year_ID_not_Found", resourceCulture);
            }
        }
    }
}
